-- Очистка всех таблиц
TRUNCATE TABLE clients_arenda RESTART IDENTITY CASCADE;
TRUNCATE TABLE clients_pokupka RESTART IDENTITY CASCADE;
TRUNCATE TABLE clients_prodaja RESTART IDENTITY CASCADE;
TRUNCATE TABLE properties RESTART IDENTITY CASCADE;
TRUNCATE TABLE tasks RESTART IDENTITY CASCADE;
TRUNCATE TABLE deals RESTART IDENTITY CASCADE;
TRUNCATE TABLE activity RESTART IDENTITY CASCADE;
TRUNCATE TABLE notifications RESTART IDENTITY CASCADE;

-- Профили не трогаем — они нужны для входа
