-- Чинит сиквенсы identity-колонок после миграции (сгенерировано, max id на момент переезда).
ALTER TABLE client_activity ALTER COLUMN id RESTART WITH 646;
ALTER TABLE clients_arenda ALTER COLUMN id RESTART WITH 3614;
ALTER TABLE clients_pokupka ALTER COLUMN id RESTART WITH 31;
ALTER TABLE clients_prodaja ALTER COLUMN id RESTART WITH 74;
ALTER TABLE deals_kvartiry ALTER COLUMN id RESTART WITH 41;
ALTER TABLE deals_pomescheniya ALTER COLUMN id RESTART WITH 4;
ALTER TABLE deals_zemlya ALTER COLUMN id RESTART WITH 15;
ALTER TABLE districts ALTER COLUMN id RESTART WITH 6;
ALTER TABLE lists ALTER COLUMN id RESTART WITH 12;
ALTER TABLE notifications ALTER COLUMN id RESTART WITH 863;
ALTER TABLE objects ALTER COLUMN id RESTART WITH 78085;
ALTER TABLE profiles ALTER COLUMN id RESTART WITH 26;
ALTER TABLE residential_complexes ALTER COLUMN id RESTART WITH 80;
ALTER TABLE tasks ALTER COLUMN id RESTART WITH 46;
